language: node_js
node_js:
  - "6"
  - "6.1"
  - "5.11"
  - "4"
install:
    - npm install -d
    - npm install -g jshint
    - npm install -g mocha
script:
    - make test
    - ./node_modules/.bin/istanbul-coveralls
