apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fake-expat-claim-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fake-expat-claim-service
    spec:
      containers:
        - name: fake-expat-claim-service
          image: 192.168.99.45:2376/fake-expat-claim-service:v4
          ports:
            - containerPort: 8000
