apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fake-expat-claim-service
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: fake-expat-claim-service
    spec:
      containers:
        - name: fake-expat-claim-service
          image: fake-expat-claim-service:v2
          ports:
            - containerPort: 8000
